# Kaggle Competition - Quant & Machine Learning Course
# Tutorial 11: Stacking Models by Any ML Model

In [1]:
# compare ensemble to each standalone models for regression
from numpy import mean
from numpy import std
from sklearn.datasets import make_regression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import StackingRegressor
from matplotlib import pyplot
 
# get the dataset
# a simulated dataset
def get_dataset():
	X, y = make_regression(n_samples=1000, n_features=20, n_informative=15, noise=0.1, random_state=1)
	return X, y

In [2]:
# define dataset
X, y = get_dataset()
print(X.shape)
print(X[:2])
print(y[:2])

(1000, 20)
[[ 0.59332206 -0.56637507  1.34808718 -0.57054047 -0.72480487  1.05648449
   0.77744852  0.07361796  0.88398267  2.02843157  1.01902732  0.11227799
   0.94218853  0.26741783  0.91458143 -0.72759572  1.08842814 -0.61450942
  -0.69387293  1.69169009]
 [ 0.02335703  1.31289541 -0.10889847  1.29099337  0.88608992  1.04003845
  -1.56111989  0.26486763  0.3093178   0.07983961 -0.8311734  -0.39712568
   0.31897183  0.52795055 -0.56398646  0.93755484  2.91730876  0.57326545
   1.15321262  1.0986885 ]]
[419.49285417 524.80418832]


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

In [4]:
#define level0 models
model_0 = KNeighborsRegressor()
model_1 = KNeighborsRegressor(n_neighbors=3)
model_2 = KNeighborsRegressor(n_neighbors=10)

model_3 = DecisionTreeRegressor(max_depth=3)
model_4 = DecisionTreeRegressor(max_leaf_nodes=6)

model_5 = SVR()

In [5]:
models = [model_0,model_1,model_2,model_3,model_4,model_5]
y_train.shape
import numpy as np
pred_trains = np.empty((y_train.shape[0],1), int)

pred_trains.shape

(750, 1)

In [6]:
import numpy as np
pred_trains = np.empty((y_train.shape[0],1), int)

for model in models:
    print(model)
    model.fit(X_train,y_train)
    print(model.score(X_train,y_train))
    pred_y= model.predict(X_train).reshape(y_train.shape[0],1)
    pred_trains = np.append(pred_trains, pred_y, axis=1)
    print(pred_trains.shape)
pred_trains = pred_trains[:,2:]

KNeighborsRegressor()
0.7541001518036443
(750, 2)
KNeighborsRegressor(n_neighbors=3)
0.7888165557943176
(750, 3)
KNeighborsRegressor(n_neighbors=10)
0.7245749595763051
(750, 4)
DecisionTreeRegressor(max_depth=3)
0.4174047211963756
(750, 5)
DecisionTreeRegressor(max_leaf_nodes=6)
0.36346481254486085
(750, 6)
SVR()
0.08222996437035845
(750, 7)


In [7]:
print(pred_trains[1:3])
print(y_train[1:3])

[[-370.54930782 -279.05509698 -239.90923965 -239.90923965  -27.73486625]
 [ 163.85728815  168.67632202  263.71009994  177.69262823    6.72960366]]
[-579.77215699   95.38288558]


In [8]:
#import xgboost
combine_model = LinearRegression()
#combine_model = xgboost.XGBRegressor()

combine_model.fit(pred_trains, y_train)
print(combine_model.coef_)
print(combine_model.intercept_)
print(combine_model.score(pred_trains,y_train))

[ 0.21375907  0.33368577  0.08334029 -0.04455886 13.97025062]
-39.662647995597126
0.9321451420507632


In [10]:
pred_tests = np.empty((y_test.shape[0],1), int)

for model in models:
    print(model)
    pred_y= model.predict(X_test).reshape(y_test.shape[0],1)
    print(model.score(X_test,y_test))
    pred_tests = np.append(pred_tests, pred_y, axis=1)
pred_tests = pred_tests[:,2:]
    
combine_pred_test = combine_model.predict(pred_tests)
print(combine_model)
print(combine_model.score(pred_tests,y_test))

KNeighborsRegressor()
0.6394976677229471
KNeighborsRegressor(n_neighbors=3)
0.5517682017597703
KNeighborsRegressor(n_neighbors=10)
0.6463810789490669
DecisionTreeRegressor(max_depth=3)
0.22779343491398607
DecisionTreeRegressor(max_leaf_nodes=6)
0.16978396781584515
SVR()
0.07523233038622357
LinearRegression()
0.8946323451471271
